// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using csula.labs.HW2.Services;

#nullable disable

namespace csula.labs.HW2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("csula.labs.HW2.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FirstDose")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SecondDose")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VaccineCompanyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VaccineCompanyId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("csula.labs.HW2.Models.Vaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DosesInBetween")
                        .HasColumnType("int");

                    b.Property<int>("DosesRecieved")
                        .HasColumnType("int");

                    b.Property<int>("DosesRequired")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalDosesLeft")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vaccines");
                });

            modelBuilder.Entity("csula.labs.HW2.Models.Patient", b =>
                {
                    b.HasOne("csula.labs.HW2.Models.Vaccine", "VaccineCompany")
                        .WithMany("Patients")
                        .HasForeignKey("VaccineCompanyId");

                    b.Navigation("VaccineCompany");
                });

            modelBuilder.Entity("csula.labs.HW2.Models.Vaccine", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
